#  Assignment 5

This assignment covers material on matrices, norms, condition numbers and eigensystems.

The breakdown of the marks is as follows:

Question 0 - [1 mark]  
Question 1 - [7 marks]  
Questino 2 - [6 marks]  
Question 3 - [7 marks]  
Question 4 - [9 marks]  

# Question 0

You should have saved this notebook to your ACM20030-Assignments folder. Now:
- commit the notebook to your local repository
- push the changes to the GitHub

In [1]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(linewidth=200)  # This stops line wrapping of larger matrices

# Question 1 - practice manipulating arrays

This questions asks you write a few functions for manipulating arrays of data

## Q1 a

Write a function that checks if a given $n\times n$ matrix is symmetric. Use only loops and `.shape` function from numpy (do not use any other special numpy functions).

In [20]:
def checksym(x):
    #first find the shape of the matrix and define i and j
    n = x.shape[0] - 1
    i = 0
    j = 0
    #next compare each element [i,j] with its transpose [j,i]
    while i <= n:
        if x[i,j] != x[j,i]:
            return "matrix is not symmetric"
        #any time [i,j] != [j,i] we know the matrix is not symmetric
        else:
            #check that this is the case for all values of i and j
            while j <= n:
                j += 1
            if j > n:
                j = 0
                i += 1
            if i > n:
                return "matrix is symmetric"
            #at this point all values have been checked and since [i,j] == [j,i] for all we can say that the matrix is symmetrical
            
    

A = np.array([[1,0,0], [0,1,0], [0,0,1]])
checksym(A)

'matrix is symmetric'

Test your function on the two matrices below

In [23]:
A = np.random.rand(5,5)
SymMatrix = (A + A.T)/2

In [31]:
#first lets observe whether A is symmetrical
A

array([[0.39198396, 0.21230857, 0.73373848, 0.9533695 , 0.12090167],
       [0.02596138, 0.39691659, 0.86249849, 0.3692704 , 0.84429128],
       [0.66088962, 0.23904655, 0.6728002 , 0.87827753, 0.66218175],
       [0.69210153, 0.90013142, 0.23775551, 0.09326545, 0.99891966],
       [0.57206827, 0.68208113, 0.43835647, 0.00662544, 0.55666311]])

In [32]:
#A is clearly not symmetrical 
#lets see if the function agrees
checksym(A)

'matrix is not symmetric'

In [33]:
#lets check if SymMatrix is symmetrical
SymMatrix

array([[0.39198396, 0.11913497, 0.69731405, 0.82273552, 0.34648497],
       [0.11913497, 0.39691659, 0.55077252, 0.63470091, 0.76318621],
       [0.69731405, 0.55077252, 0.6728002 , 0.55801652, 0.55026911],
       [0.82273552, 0.63470091, 0.55801652, 0.09326545, 0.50277255],
       [0.34648497, 0.76318621, 0.55026911, 0.50277255, 0.55666311]])

In [34]:
#its clearly symmetrical
#lets check if the function agrees
checksym(SymMatrix)

'matrix is symmetric'

## Q1 b

Write a function to transpose a general $n\times n$ matrix. Do this by writing loops and not using any special functions like `np.transpose()`, `A.T`, or any functions from any other library (`np.zeroes`, `np.ones`, `np.shape`, etc are all ok to use).

In [52]:
def transpose(x):
    #first find the shape of the matrix and define i and j
    n = x.shape[0] - 1
    i = 0
    j = 0
    #create a matrix of 0's in the same shape as x
    x0 = np.zeros(x.shape)
    #add the transpose of x to the matrix of 0's
    while i <= n:
        x0[i,j] = x0[i,j] + x[j,i]
        j += 1
        if j > n:
            j = 0
            i += 1
    else:
        return x0
    #return the new transposed matrix   

Check your code by transposing a matrix by checking that $A^T \neq A$ and $(A^T)^T - A = 0$

In [53]:
A = np.random.rand(6,6);
print(A)
print(transpose(A))
#its clear transpose(A) != A

[[0.40739859 0.39782463 0.57727712 0.10230771 0.63521237 0.54676599]
 [0.19644704 0.20316711 0.84763305 0.98577028 0.7246435  0.02660007]
 [0.39313585 0.63336233 0.80272476 0.2586161  0.82293783 0.86156878]
 [0.10093981 0.27400553 0.19072418 0.19180086 0.2169153  0.62009692]
 [0.16199    0.6971819  0.24359422 0.00494373 0.54513749 0.83809201]
 [0.22092782 0.91269053 0.10766696 0.58057385 0.50166204 0.01215773]]
[[0.40739859 0.19644704 0.39313585 0.10093981 0.16199    0.22092782]
 [0.39782463 0.20316711 0.63336233 0.27400553 0.6971819  0.91269053]
 [0.57727712 0.84763305 0.80272476 0.19072418 0.24359422 0.10766696]
 [0.10230771 0.98577028 0.2586161  0.19180086 0.00494373 0.58057385]
 [0.63521237 0.7246435  0.82293783 0.2169153  0.54513749 0.50166204]
 [0.54676599 0.02660007 0.86156878 0.62009692 0.83809201 0.01215773]]


In [54]:
#next check that transpose(transpose(A)) - A == 0
transpose(transpose(A)) - A == 0

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

## Q1c

Write a function that finds the maximum entry in a matrix (where the matrix does not need to be square). Do this by writing loops and not using any special functions like `np.max` or any functions from any other library.

In [58]:
def max(x):
    n = x.shape[0] - 1
    m = x.shape[1] - 1
    i = 0
    j = 0
    a = x[0,0]
    while i <= n:
        if x[i,j] > a:
            a = x[i,j]
        j += 1
        if j > m:
            j = 0
            i += 1
        
    else:
        return a

Check your result by comparing to `np.max(A)` for the below random matrix

In [59]:
A = np.random.rand(4,5)

print(np.max(A))
print(max(A))

0.9682685964740846
0.9682685964740846


Commit your notebook to git and push it to GitHub.

# Question 2:  matrix norms

In the lectures we focused on the $L^2$-norm. We also briefly mentioned the $L^1$ and $L^\infty$ norm. Let's look at calculating those as well for a general $m\times n$ matrix.

# Q2a

The $L^1$ norm is given by

$$ \lVert A \rVert_1 = \max_j \sum^m_{i=1} |a_{ij}| $$

i.e., it is the max of the sums of the absolute values of each column. Write a function that computes the $L^1$-norm using only loops. The function should use no special numpy functions except `np.abs()` (`np.shape`, `np.inf`, etc are ok to use).

Check your result against NumPy's `la.norm(A,1)` function for the following random matrix

In [5]:
A = np.random.rand(3,4)


## Q2b

The $L^\infty$ norm is given by 

$$\lVert A \rVert_\infty = \max_i \sum_{j=1}^n |a_{ij}|$$

i.e., it is the max of the sums of the absolute values of each row. Write a function that computes the $L^\infty$-norm using only loops and no special numpy functions.

Check your result against NumPy's `la.norm(A,np.inf)` function for the following random matrix

In [6]:
A = np.random.rand(3,4)



Commit your notebook to git and push it to GitHub.

# Question 3: ill-conditions systems of equations

In this question you can use any of NumPy's functions.

## Q3a

Which of the following three matrices, $A1, A2, A3$, are ill-conditioned. State the reason for your conclusion.

In [7]:
A1 = np.array([[ 2.852416473483e-01,  3.803483118694e-01,  2.697704226632e-01,  6.810611849029e-01],
       [ 6.622827828376e-01,  6.447943415836e-01,  4.387842058829e-01,  1.530575702376e+00],
       [ 3.672130860703e-01,  8.309522079704e-01,  9.975487474007e-01,  5.678296337101e-01],
       [ 4.036490000599e-01,  6.865978225967e-06,  8.788095913773e-01, -7.150472427928e-02]])

A2 = np.array([[0.988746460106, 0.351486109477, 0.024911477532, 0.384039749683],
       [0.282104657306, 0.239884151775, 0.36170151991 , 0.903082266861],
       [0.59333290915 , 0.637178863968, 0.241229214635, 0.685595037901],
       [0.013591747828, 0.917926970364, 0.458689093885, 0.157821121254]])

A3 = np.array([[0.131923621844, 0.245316154195, 0.732362341613, 0.957047891764],
       [0.91290446184 , 0.512312007959, 0.391938831444, 0.092509684772],
       [0.648708523652, 0.608576675797, 0.576773587276, 0.065385122929],
       [0.502955480393, 0.084082960221, 0.659487390444, 0.662958739412]])

# Q3b

With $b = [1,2,3,4]$ and $\delta b = [0.1,0,0,0]$ for $A1$ and $A2$ calculate the percentage change in $x$ due to a small change in $b$, i.e., calculate 

$$100\times\frac{\lVert \delta x_i\rVert_2}{\lVert x_i \rVert_2}\quad\text{and}\quad 100\times\frac{\lVert \delta b\rVert_2}{\lVert b \rVert_2}$$

where $(x_i+\delta x_i)  = A_i^{-1}(b+\delta b)$ and $i\in\{1,2\}$.

Which system of equations is more sensitive to small changes in $b$? How could you have guessed this from the answer to the Q3a?

In [8]:
# Answer here


Commit your notebook to git and push it to GitHub.

# Question 4: eigensystems

In this question we look at finding eigenvalues and eigenvectors

## Q4a

You may use any of NumPy's functions for this sub-question.

Find the eigenvalues and eigenvectors for the below matrix. Print out the eigenvalues sorted by descending value and explicitly show that eigenvalues/eigenvector pairs satisfy $Ax = \lambda x$.

In [50]:
A = np.array([[1,4,5],[4,5,4],[6,7,9]])

# Q4b

Without using NumPy's `la.eig()` (or similar functions), find the 4 eigenvalues and eigenvectors of the following matrix. Hint: Use the power method for the max eigenvalue (given below in `MaxEigenvalue`), the power method applied to the inverse for the smallest eigenvalue, and apply Hotelling's deflation twice to find the second and third eigenvalues/eigenvectors.

In [20]:
A = np.array([[2.65287619, 1.58615494, 1.47170961, 1.40586081],
       [1.58615494, 1.17577323, 0.72084593, 0.79382861],
       [1.47170961, 0.72084593, 1.18111969, 0.6654689 ],
       [1.40586081, 0.79382861, 0.6654689 , 0.84502394]])

Check your answers against Numpy's results from `la.eig(A)`

Commit your notebook to git and push it to GitHub. Upload your completed assignment to BrightSpace.