#  Assignment 5

This assignment covers material on matrices, norms, condition numbers and eigensystems.

The breakdown of the marks is as follows:

Question 0 - [1 mark]  
Question 1 - [7 marks]  
Questino 2 - [6 marks]  
Question 3 - [7 marks]  
Question 4 - [9 marks]  

# Question 0

You should have saved this notebook to your ACM20030-Assignments folder. Now:
- commit the notebook to your local repository
- push the changes to the GitHub

In [53]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(linewidth=200)  # This stops line wrapping of larger matrices

# Question 1 - practice manipulating arrays

This questions asks you write a few functions for manipulating arrays of data

## Q1 a

Write a function that checks if a given $n\times n$ matrix is symmetric. Use only loops and `.shape` function from numpy (do not use any other special numpy functions).

In [54]:
def checksym(x):
    #first find the shape of the matrix and define i and j
    n = x.shape[0] - 1
    i = 0
    j = 0
    #next compare each element [i,j] with its transpose [j,i]
    while i <= n:
        if x[i,j] != x[j,i]:
            return "matrix is not symmetric"
        #any time [i,j] != [j,i] we know the matrix is not symmetric
        else:
            #check that this is the case for all values of i and j
            while j <= n:
                j += 1
            if j > n:
                j = 0
                i += 1
            if i > n:
                return "matrix is symmetric"
            #at this point all values have been checked and since [i,j] == [j,i] for all we can say that the matrix is symmetric
            
    

A = np.array([[1,0,0], [0,1,0], [0,0,1]])
checksym(A)

'matrix is symmetric'

Test your function on the two matrices below

In [55]:
A = np.random.rand(5,5)
SymMatrix = (A + A.T)/2

In [56]:
#first lets observe whether A is symmetrical
A

array([[0.57629687, 0.34573789, 0.6415468 , 0.08371718, 0.91262476],
       [0.31055971, 0.64757014, 0.5281847 , 0.2218241 , 0.2623515 ],
       [0.50680944, 0.6594472 , 0.65576348, 0.3232597 , 0.02824675],
       [0.87557191, 0.62390114, 0.49022851, 0.51728773, 0.99095348],
       [0.01453482, 0.14265996, 0.76680429, 0.93704333, 0.65178539]])

In [57]:
#A is clearly not symmetrical 
#lets see if the function agrees
checksym(A)

'matrix is not symmetric'

In [58]:
#lets check if SymMatrix is symmetrical
SymMatrix

array([[0.57629687, 0.3281488 , 0.57417812, 0.47964455, 0.46357979],
       [0.3281488 , 0.64757014, 0.59381595, 0.42286262, 0.20250573],
       [0.57417812, 0.59381595, 0.65576348, 0.4067441 , 0.39752552],
       [0.47964455, 0.42286262, 0.4067441 , 0.51728773, 0.9639984 ],
       [0.46357979, 0.20250573, 0.39752552, 0.9639984 , 0.65178539]])

In [59]:
#its clearly symmetrical
#lets check if the function agrees
checksym(SymMatrix)

'matrix is symmetric'

## Q1 b

Write a function to transpose a general $n\times n$ matrix. Do this by writing loops and not using any special functions like `np.transpose()`, `A.T`, or any functions from any other library (`np.zeroes`, `np.ones`, `np.shape`, etc are all ok to use).

In [60]:
def transpose(x):
    #first find the shape of the matrix and define i and j
    n = x.shape[0] - 1
    i = 0
    j = 0
    #create a matrix of 0's in the same shape as x
    x0 = np.zeros(x.shape)
    #add the transpose of x to the matrix of 0's
    while i <= n:
        x0[i,j] = x0[i,j] + x[j,i]
        j += 1
        if j > n:
            j = 0
            i += 1
    else:
        return x0
    #return the new transposed matrix   

Check your code by transposing a matrix by checking that $A^T \neq A$ and $(A^T)^T - A = 0$

In [61]:
A = np.random.rand(6,6);
print(A)
print(transpose(A))
#its clear transpose(A) != A

[[0.78574673 0.99401678 0.30829567 0.55885045 0.80875786 0.29982829]
 [0.47602668 0.59752013 0.06720847 0.51222826 0.0772405  0.77560735]
 [0.52340817 0.28518611 0.51073991 0.06812319 0.79064064 0.31152156]
 [0.55975889 0.95665666 0.77327075 0.898829   0.0571723  0.81368225]
 [0.69890876 0.34972783 0.64387023 0.73915659 0.5023205  0.74963162]
 [0.01672392 0.42652169 0.78837876 0.89539607 0.77240074 0.15405499]]
[[0.78574673 0.47602668 0.52340817 0.55975889 0.69890876 0.01672392]
 [0.99401678 0.59752013 0.28518611 0.95665666 0.34972783 0.42652169]
 [0.30829567 0.06720847 0.51073991 0.77327075 0.64387023 0.78837876]
 [0.55885045 0.51222826 0.06812319 0.898829   0.73915659 0.89539607]
 [0.80875786 0.0772405  0.79064064 0.0571723  0.5023205  0.77240074]
 [0.29982829 0.77560735 0.31152156 0.81368225 0.74963162 0.15405499]]


In [62]:
#next check that transpose(transpose(A)) - A == 0
transpose(transpose(A)) - A == 0

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

## Q1c

Write a function that finds the maximum entry in a matrix (where the matrix does not need to be square). Do this by writing loops and not using any special functions like `np.max` or any functions from any other library.

In [63]:
def max(x):
    #find shape and define i and j
    m = x.shape[0] - 1
    n = x.shape[1] - 1
    i = 0
    j = 0
    a = x[0,0]
    while i <= m:
        #going through every x[i,j] when we find a value greater than our previous max value that becomes the new max value
        if x[i,j] > a:
            a = x[i,j]
        j += 1
        if j > n:
            j = 0
            i += 1
       
    #when weve gone through every element of the matrix print a, our current and final max value. 
    else:
        return a

Check your result by comparing to `np.max(A)` for the below random matrix

In [64]:
A = np.random.rand(4,5)

print(np.max(A))
print(max(A))

0.988972350471296
0.988972350471296


Commit your notebook to git and push it to GitHub.

# Question 2:  matrix norms

In the lectures we focused on the $L^2$-norm. We also briefly mentioned the $L^1$ and $L^\infty$ norm. Let's look at calculating those as well for a general $m\times n$ matrix.

# Q2a

The $L^1$ norm is given by

$$ \lVert A \rVert_1 = \max_j \sum^m_{i=1} |a_{ij}| $$

i.e., it is the max of the sums of the absolute values of each column. Write a function that computes the $L^1$-norm using only loops. The function should use no special numpy functions except `np.abs()` (`np.shape`, `np.inf`, etc are ok to use).

In [65]:
def L1(x):
    #find the shape and define i and j
    m = x.shape[0] - 1
    n = x.shape[1] - 1
    i = 0 
    j = 0
    a = 0
    #create a 1xn matrix of zeros that we can make our matrix of the sums of the j columns
    b = np.zeros((1,n + 1))
    #c will be the max value of our matrix b
    c = b[0,0]
    while j <= n:
        #we will add all the absolute values of each column to b
        b[0,a] += np.abs(x[i,j])
        i += 1
        #in the case where an element of b is greater than the previous max this element is the new max
        if i > m:
            i = 0
            j += 1
            if b[0,a] > c:
                c = b[0,a]
            a += 1
       
        
    #now that the sum of all elements has been calculated we print c
    else:
        return c

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
L1(A)

18.0

Check your result against NumPy's `la.norm(A,1)` function for the following random matrix

In [66]:
A = np.random.rand(3,4)
print(la.norm(A, 1))
print(L1(A))

1.9028067094376964
1.9028067094376964


## Q2b

The $L^\infty$ norm is given by 

$$\lVert A \rVert_\infty = \max_i \sum_{j=1}^n |a_{ij}|$$

i.e., it is the max of the sums of the absolute values of each row. Write a function that computes the $L^\infty$-norm using only loops and no special numpy functions.

In [67]:
def Linf(x):
    #find the shape and define i and j
    m = x.shape[0] - 1
    n = x.shape[1] - 1
    i = 0 
    j = 0
    a = 0
    #create a 1xn matrix of zeros that we can make our matrix of the sums of the i rows
    b = np.zeros((1,n + 1))
    #c will be the max value of our matrix b
    c = b[0,0]
    while i <= m:
        #we will add all the absolute values of each row to b
        b[0,a] += np.abs(x[i,j])
        j += 1
        #in the case where an element of b is greater than the previous max this element is the new max
        if j > n:
            j = 0
            i += 1
            if b[0,a] > c:
                c = b[0,a]
            a += 1
       
        
    #now that the sum of all elements has been calculated we print c
    else:
        return c


Check your result against NumPy's `la.norm(A,np.inf)` function for the following random matrix

In [68]:
A = np.random.rand(3,4)
print(la.norm(A,np.inf))
print(Linf(A))


2.7475296931679765
2.7475296931679765


Commit your notebook to git and push it to GitHub.

# Question 3: ill-conditions systems of equations

In this question you can use any of NumPy's functions.

## Q3a

Which of the following three matrices, $A1, A2, A3$, are ill-conditioned. State the reason for your conclusion.

In [69]:
A1 = np.array([[ 2.852416473483e-01,  3.803483118694e-01,  2.697704226632e-01,  6.810611849029e-01],
       [ 6.622827828376e-01,  6.447943415836e-01,  4.387842058829e-01,  1.530575702376e+00],
       [ 3.672130860703e-01,  8.309522079704e-01,  9.975487474007e-01,  5.678296337101e-01],
       [ 4.036490000599e-01,  6.865978225967e-06,  8.788095913773e-01, -7.150472427928e-02]])

A2 = np.array([[0.988746460106, 0.351486109477, 0.024911477532, 0.384039749683],
       [0.282104657306, 0.239884151775, 0.36170151991 , 0.903082266861],
       [0.59333290915 , 0.637178863968, 0.241229214635, 0.685595037901],
       [0.013591747828, 0.917926970364, 0.458689093885, 0.157821121254]])

A3 = np.array([[0.131923621844, 0.245316154195, 0.732362341613, 0.957047891764],
       [0.91290446184 , 0.512312007959, 0.391938831444, 0.092509684772],
       [0.648708523652, 0.608576675797, 0.576773587276, 0.065385122929],
       [0.502955480393, 0.084082960221, 0.659487390444, 0.662958739412]])

In [70]:
print("the condition number of A1 is", la.cond(A1))
print("the condition number of A2 is", la.cond(A2))
print("the condition number of A3 is", la.cond(A3))

the condition number of A1 is 13334936994.070848
the condition number of A2 is 21.552466488381846
the condition number of A3 is 15.12244969941062


#### therefore we see the condition number of each matrix is greater than 1 so all 3 matrices are ill-conditioned

# Q3b

With $b = [1,2,3,4]$ and $\delta b = [0.1,0,0,0]$ for $A1$ and $A2$ calculate the percentage change in $x$ due to a small change in $b$, i.e., calculate 

$$100\times\frac{\lVert \delta x_i\rVert_2}{\lVert x_i \rVert_2}\quad\text{and}\quad 100\times\frac{\lVert \delta b\rVert_2}{\lVert b \rVert_2}$$

where $(x_i+\delta x_i)  = A_i^{-1}(b+\delta b)$ and $i\in\{1,2\}$.

In [71]:
b1 = np.array([1,2,3,4])
delta_b = np.array([0.1,0,0,0])
b2 = b1 + delta_b
x1 = la.inv(A1)@b1
x2 = la.inv(A2)@b1
delta_x1 = la.inv(A1)@b2 - x1
delta_x2 = la.inv(A2)@b2 - x2

solA1_x = 100*(la.norm(delta_x1,2)/la.norm(x1,2))
solA2_x = 100*(la.norm(delta_x2,2)/la.norm(x2,2))

sol_b = 100*(la.norm(delta_b,2)/la.norm(b1,2))

print(solA1_x,sol_b)
print(solA2_x,sol_b)

512.6206098890646 1.8257418583505536
10.48358222033912 1.8257418583505536


Which system of equations is more sensitive to small changes in $b$? How could you have guessed this from the answer to the Q3a?

In [72]:
# Answer here
# A1 is more sensitive to small change in b. This was obvious from 3a as its condition number was by far the largest.


Commit your notebook to git and push it to GitHub.

# Question 4: eigensystems

In this question we look at finding eigenvalues and eigenvectors

## Q4a

You may use any of NumPy's functions for this sub-question.

Find the eigenvalues and eigenvectors for the below matrix. Print out the eigenvalues sorted by descending value and explicitly show that eigenvalues/eigenvector pairs satisfy $Ax = \lambda x$.

In [73]:
A = np.array([[1,4,5],[4,5,4],[6,7,9]])

In [74]:
#first we print the eigenvalues
evals = la.eig(A)[0]
evals

array([15.78569318, -2.05164645,  1.26595327])

In [75]:
#next the corresponding eigenvectors
evecs = la.eig(A)[1]
evecs

array([[-0.39252008, -0.89589878,  0.09818766],
       [-0.44424151,  0.36255198, -0.77454142],
       [-0.80534308,  0.25675168,  0.6248558 ]])

In [76]:
#well check that Ax = lamx for all eigenvalues
#no. 1
lam = evals[0]
x = evecs[:,0]
print("Ax =", np.dot(A, x)) 
print("lamx =", lam*x) 

Ax = [ -6.1962015   -7.01266016 -12.71289871]
lamx = [ -6.1962015   -7.01266016 -12.71289871]


In [77]:
#no. 2
lam = evals[1]
x = evecs[:,1]
print("Ax =", np.dot(A, x)) 
print("lamx =", lam*x) 

Ax = [ 1.83806756 -0.74382849 -0.52676368]
lamx = [ 1.83806756 -0.74382849 -0.52676368]


In [78]:
#no. 3
lam = evals[2]
x = evecs[:,2]
print("Ax =", np.dot(A, x)) 
print("lamx =", lam*x) 

Ax = [ 0.12430099 -0.98053324  0.79103825]
lamx = [ 0.12430099 -0.98053324  0.79103825]


# Q4b

Without using NumPy's `la.eig()` (or similar functions), find the 4 eigenvalues and eigenvectors of the following matrix. Hint: Use the power method for the max eigenvalue (given below in `MaxEigenvalue`), the power method applied to the inverse for the smallest eigenvalue, and apply Hotelling's deflation twice to find the second and third eigenvalues/eigenvectors.

In [79]:
A = np.array([[2.65287619, 1.58615494, 1.47170961, 1.40586081],
       [1.58615494, 1.17577323, 0.72084593, 0.79382861],
       [1.47170961, 0.72084593, 1.18111969, 0.6654689 ],
       [1.40586081, 0.79382861, 0.6654689 , 0.84502394]])

In [80]:
def MaxEigenvalue(A, err):
    (m,n) = A.shape
    if(m != n):
        print("matrix must be square")
        return
    
    #create a random initial vector
    x = np.random.rand(m)
    
    lam = 0.1
    lamprev = 1
    while np.abs(1-lam/lamprev) > err:
        Ax = A@x
        lamprev = lam
        lam = la.norm(Ax,2)/la.norm(x,2)
        x = Ax
        
    x = x/la.norm(x)
    return (lam,x)

In [81]:
print("max eigenvalue =", MaxEigenvalue(A, 1e-14)[0])
print("corresponding eigenvector =", MaxEigenvalue(A, 1e-14)[1])
eig1 = MaxEigenvalue(A, 1e-14)

max eigenvalue = 5.172971199844757
corresponding eigenvector = [0.71538265 0.43087578 0.40381884 0.37350243]


In [87]:
print("min eigenvalue =", 1/MaxEigenvalue(la.inv(A), 1e-14)[0])
print("corresponding eigenvector =", MaxEigenvalue(la.inv(A), 1e-14)[1])
eig2 = (1/MaxEigenvalue(la.inv(A), 1e-14)[0],MaxEigenvalue(la.inv(A), 1e-14)[1])

min eigenvalue = 0.0015297971635957477
corresponding eigenvector = [-0.68301529  0.34802856  0.328043    0.55204531]


In [88]:
l1 = MaxEigenvalue(A, 1e-14)[0]
e1 = MaxEigenvalue(A, 1e-14)[1]
B = A - l1*np.outer(e1, e1)
print("second eigenvalue =", MaxEigenvalue(B, 1e-14)[0])
print("corresponding eigenvector =", MaxEigenvalue(B, 1e-14)[1])
eig4 = MaxEigenvalue(B, 1e-14)

second eigenvalue = 0.4816692703106537
corresponding eigenvector = [-0.04054567 -0.52331842  0.82477029 -0.21035172]


In [89]:
l2 = MaxEigenvalue(B, 1e-14)[0]
e2 = MaxEigenvalue(B, 1e-14)[1]
B2 = B - l2*np.outer(e2, e2)
print("third eigenvalue =", MaxEigenvalue(B2, 1e-14)[0])
print("corresponding eigenvector =", MaxEigenvalue(B2, 1e-14)[1])
eig3 = MaxEigenvalue(B2, 1e-14)

third eigenvalue = 0.19862278268099323
corresponding eigenvector = [ 0.14168212 -0.64758015 -0.22152218  0.71518812]


Check your answers against Numpy's results from `la.eig(A)`

In [90]:
la.eig(A)
#our values for lamda and x are similiar to the values gotten from using la.eig(A)

(array([5.17297120e+00, 1.52979716e-03, 1.98622783e-01, 4.81669270e-01]),
 array([[ 0.71538265,  0.68301529,  0.14168212, -0.04054567],
        [ 0.43087578, -0.34802856, -0.64758011, -0.52331842],
        [ 0.40381884, -0.328043  , -0.22152224,  0.82477029],
        [ 0.37350243, -0.55204531,  0.71518814, -0.21035171]]))

In [91]:
#we will now write a code that tests the difference between our values and the values from la.eig(A) in lam*x
#if the results are small it shows that our values for lamda and x are close to the values gotten from using la.eig(A)
def eigtest(A):
    l = len(la.eig(A)[0])
    evals = la.eig(A)[0]
    evecs = la.eig(A)[1]
    
    a = 0
    b = np.array([eig1,eig2,eig3,eig4])
    
    
    lam = evals[a]
    x = evecs[:,a]
    
    lam2 = b[a,0]
    x2 = b[a,1]
    while a < l:
        return lam2*x2 - lam*x
        a += 1
    
eigtest(A)

array([-7.88191734e-11, -1.01669828e-09,  1.60263891e-09, -4.08892031e-10])

Commit your notebook to git and push it to GitHub. Upload your completed assignment to BrightSpace.